// Auto-generated by `dakiya init` — gives you full IDE autocomplete in scripts.
// Do not edit manually; re-run `dakiya init` to regenerate.

declare module "dakiya/scripts" {
  /** Mutable view of the outgoing HTTP request. */
  export interface ReqApi {
    method: string;
    url: string;
    /** The parsed request body — cast to the shape you need. */
    body: unknown;
    getHeader(name: string): string | undefined;
    setHeader(name: string, value: string): void;
    removeHeader(name: string): void;
  }

  /** Read-only view of the HTTP response (post-script only). */
  export interface ResApi {
    readonly status: number;
    readonly statusText: string;
    /** Raw response body string. */
    readonly body: string;
    /** Parse the response body as JSON. */
    json(): unknown;
    getHeader(name: string): string | undefined;
    setHeader(name: string, value: string): void;
  }

  /** Environment variable bag — read, write, and persist values. */
  export interface EnvApi {
    get(name: string): string | undefined;
    /** @param options.persist — if true, the value is saved back to the .yaml env file. */
    set(name: string, value: string, options?: { persist?: boolean }): void;
    delete(name: string): void;
  }

  /** Request metadata available in all scripts. */
  export interface ScriptMeta {
    /** Human-readable request name (e.g. "login"). */
    requestName: string;
    /** Path relative to collections root (e.g. "auth/login/post"). */
    requestPath: string;
    phase: "pre" | "post";
    /** Unique UUID generated per request send — useful for correlation. */
    traceId: string;
    /** Elapsed ms from send start. Only present in @post scripts. */
    durationMs?: number;
  }

  /** Context object passed to pre-request scripts. */
  export interface PreContext {
    req: ReqApi;
    env: EnvApi;
    meta: ScriptMeta & { phase: "pre" };
  }

  /** Context object passed to post-request scripts. */
  export interface PostContext {
    req: ReqApi;
    res: ResApi;
    env: EnvApi;
    meta: ScriptMeta & { phase: "post"; durationMs: number };
  }
}
